version: 2

defaults: &defaults
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile" }}
            - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Fix CircleCI URLs
          command: cd .circleci && python urls.py /home/circleci/repo
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - store_artifacts:
          path: ./_site
          destination: _site
